name: Test self-hosted runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print versions
        run: |
          echo "Node.js version:"
          node -v
          echo "Docker version:"
          docker --version
